# Nixpacks configuration for Django on Railway
# - Installs ffmpeg for audio processing (SpeechBrain conversion)
# - Installs dependencies from django/requirements.txt
# - Starts Daphne ASGI server

[phases.setup]
nixPkgs = ["...", "ffmpeg", "pkg-config"]

[phases.install]
# Install strictly from the Django requirements to avoid conflicting root requirements
cmds = [
  "python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install --upgrade pip setuptools wheel && ( [ -f django/requirements.txt ] && pip install -r django/requirements.txt || pip install -r requirements.txt )"
]

[start]
# Start from django directory to ensure correct BASE_DIR resolution
cmd = "cd django && daphne -b 0.0.0.0 -p ${PORT:-8000} core.asgi:application"
