# Nixpacks configuration for Django on Railway
# - Installs ffmpeg for audio processing (SpeechBrain conversion)
# - Installs dependencies from django/requirements.txt
# - Starts Daphne ASGI server

[phases.setup]
nixPkgs = ["...", "ffmpeg"]

[phases.install]
# Force pip to use the available requirements file regardless of working directory
cmds = [
  "python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install --upgrade pip setuptools wheel && ( if [ -f django/requirements.txt ]; then pip install -r django/requirements.txt; elif [ -f requirements.txt ]; then pip install -r requirements.txt; else echo 'No requirements file found' && exit 1; fi )"
]

[start]
# Ensure Python can import the Django project when started from /app
cmd = "PYTHONPATH=/app/django daphne -b 0.0.0.0 -p ${PORT:-8000} core.asgi:application"
