# Nixpacks configuration for Django on Railway
# - Installs ffmpeg for audio processing (SpeechBrain conversion)
# - Installs dependencies from django/requirements.txt
# - Starts Daphne ASGI server

[phases.setup]
nixPkgs = ["...", "ffmpeg"]

[phases.install]
# Force pip to use the Django project's requirements file
cmds = [
  "python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install --upgrade pip setuptools wheel && pip install -r django/requirements.txt"
]

[start]
# Ensure Python can import the Django project when started from /app
cmd = "PYTHONPATH=/app/django daphne -b 0.0.0.0 -p ${PORT:-8000} core.asgi:application"
