# Nixpacks configuration for Django on Railway
# - Installs ffmpeg for audio processing (SpeechBrain conversion)
# - Installs dependencies from django/requirements.txt
# - Starts Daphne ASGI server

[phases.setup]
nixPkgs = ["...", "ffmpeg"]

[start]
cmd = "daphne -b 0.0.0.0 -p ${PORT:-8000} core.asgi:application"
