# Generated by Django 4.2.5 on 2025-10-15 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=100, unique=True)),
                ('definition', models.TextField()),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('example_sentence', models.TextField(blank=True, help_text='Optional example sentence')),
                ('part_of_speech', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['word'],
                'indexes': [models.Index(fields=['difficulty'], name='wordup_word_difficu_6bd93d_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserWordProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mastered', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
                ('user_example_sentence', models.TextField(blank=True)),
                ('first_attempted_at', models.DateTimeField(auto_now_add=True)),
                ('mastered_at', models.DateTimeField(blank=True, null=True)),
                ('last_practiced_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_progress', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='wordup.word')),
            ],
            options={
                'ordering': ['-last_practiced_at'],
                'indexes': [models.Index(fields=['user', 'is_mastered'], name='wordup_user_user_id_851b24_idx'), models.Index(fields=['user', '-last_practiced_at'], name='wordup_user_user_id_dd70c9_idx')],
                'unique_together': {('user', 'word')},
            },
        ),
    ]
