# Generated by Django 4.2.5 on 2025-10-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='ipa_pronunciation',
            field=models.CharField(blank=True, help_text='IPA phonetic transcription', max_length=200),
        ),
    ]
