# Generated by Django 4.2.5 on 2025-10-16 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gamification', '0002_alter_leaderboard_leaderboard_type_pointstransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('LEVEL_UP', 'LEVEL_UP'), ('TOPIC_COMPLETED', 'TOPIC_COMPLETED'), ('PROFICIENCY_TIER', 'PROFICIENCY_TIER'), ('BADGE_EARNED', 'BADGE_EARNED')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('xp_earned', models.IntegerField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievement_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'achievement_events',
                'ordering': ['-timestamp', '-id'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='achievement_user_id_48a42c_idx')],
            },
        ),
    ]
