# Generated by Django 4.2.5 on 2025-08-30 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticePrompt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(unique=True)),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('difficulty', models.CharField(choices=[('BEGINNER', 'BEGINNER'), ('INTERMEDIATE', 'INTERMEDIATE'), ('UPPER_INTERMEDIATE', 'UPPER_INTERMEDIATE'), ('ADVANCED', 'ADVANCED'), ('EXPERT', 'EXPERT')], default='BEGINNER', max_length=20)),
                ('hints', models.JSONField(blank=True, default=list)),
                ('target_duration', models.IntegerField(default=30)),
                ('cultural_context', models.TextField(blank=True, null=True)),
                ('scenario_type', models.CharField(choices=[('GENERAL', 'GENERAL'), ('BUSINESS', 'BUSINESS'), ('ACADEMIC', 'ACADEMIC'), ('SOCIAL', 'SOCIAL'), ('CULTURAL', 'CULTURAL'), ('TECHNICAL', 'TECHNICAL')], default='GENERAL', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'practice_prompts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PracticeSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audio_url', models.TextField(blank=True)),
                ('transcription', models.TextField(blank=True)),
                ('evaluation', models.JSONField(blank=True, default=dict)),
                ('score', models.FloatField(blank=True, null=True)),
                ('duration', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('EVALUATED', 'EVALUATED'), ('FAILED', 'FAILED')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='practice.practiceprompt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'practice_submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='practiceprompt',
            index=models.Index(fields=['category'], name='practice_pr_categor_c739ac_idx'),
        ),
        migrations.AddIndex(
            model_name='practiceprompt',
            index=models.Index(fields=['difficulty'], name='practice_pr_difficu_dd2b64_idx'),
        ),
        migrations.AddIndex(
            model_name='practiceprompt',
            index=models.Index(fields=['is_active'], name='practice_pr_is_acti_0c84aa_idx'),
        ),
        migrations.AddIndex(
            model_name='practicesubmission',
            index=models.Index(fields=['user', '-created_at'], name='practice_su_user_id_89d975_idx'),
        ),
        migrations.AddIndex(
            model_name='practicesubmission',
            index=models.Index(fields=['status'], name='practice_su_status_dbccc9_idx'),
        ),
    ]
