# Generated by Django 4.2.5 on 2025-10-02 02:23

import apps.users.models
import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_avatar_userfollow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='User avatar image stored in Supabase Storage', null=True, storage=core.storage.AvatarSupabaseStorage(), upload_to=apps.users.models.user_avatar_path),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_url',
            field=models.URLField(blank=True, help_text='Fallback avatar URL for external images'),
        ),
    ]
