# Generated by Django 4.2.5 on 2025-10-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_update_avatar_to_supabase'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], help_text='User gender for culturally-aware AI interactions', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='province',
            field=models.CharField(blank=True, choices=[('aceh', 'Aceh'), ('bali', 'Bali'), ('bangka_belitung', 'Bangka Belitung'), ('banten', 'Banten'), ('bengkulu', 'Bengkulu'), ('dki_jakarta', 'DKI Jakarta'), ('gorontalo', 'Gorontalo'), ('jambi', 'Jambi'), ('jawa_barat', 'Jawa Barat'), ('jawa_tengah', 'Jawa Tengah'), ('jawa_timur', 'Jawa Timur'), ('kalimantan_barat', 'Kalimantan Barat'), ('kalimantan_selatan', 'Kalimantan Selatan'), ('kalimantan_tengah', 'Kalimantan Tengah'), ('kalimantan_timur', 'Kalimantan Timur'), ('kalimantan_utara', 'Kalimantan Utara'), ('kepulauan_riau', 'Kepulauan Riau'), ('lampung', 'Lampung'), ('maluku', 'Maluku'), ('maluku_utara', 'Maluku Utara'), ('nusa_tenggara_barat', 'Nusa Tenggara Barat'), ('nusa_tenggara_timur', 'Nusa Tenggara Timur'), ('papua', 'Papua'), ('papua_barat', 'Papua Barat'), ('riau', 'Riau'), ('sulawesi_barat', 'Sulawesi Barat'), ('sulawesi_selatan', 'Sulawesi Selatan'), ('sulawesi_tengah', 'Sulawesi Tengah'), ('sulawesi_tenggara', 'Sulawesi Tenggara'), ('sulawesi_utara', 'Sulawesi Utara'), ('sumatera_barat', 'Sumatera Barat'), ('sumatera_selatan', 'Sumatera Selatan'), ('sumatera_utara', 'Sumatera Utara'), ('yogyakarta', 'DI Yogyakarta')], help_text='Indonesian province for regional socio-cultural context', max_length=50, null=True),
        ),
    ]
