# Generated by Django 4.2.5 on 2025-10-12 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_privacysettings_userblock_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('gonggong', 'Gonggong'), ('pantun', 'Pantun'), ('zapin', 'Zapin'), ('hang_nadim', 'Hang Nadim'), ('barelang', 'Barelang'), ('bulan_serindit', 'Bulan Serindit'), ('selayar', 'Selayar'), ('tanjung_ulma', 'Tanjung Ulma'), ('pulau_putri', 'Pulau Putri'), ('temiang', 'Temiang')], help_text='Batam cultural group name', max_length=50, unique=True)),
                ('display_name', models.CharField(help_text='Display name for the group', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the group and its cultural significance')),
                ('icon', models.CharField(blank=True, help_text='Icon or emoji representing the group', max_length=100)),
                ('color', models.CharField(default='#1976D2', help_text='Hex color code for the group theme', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'db_table': 'groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Message content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='users.group')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Group Message',
                'verbose_name_plural': 'Group Messages',
                'db_table': 'group_messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['group', '-created_at'], name='group_messa_group_i_78d20c_idx'), models.Index(fields=['sender', '-created_at'], name='group_messa_sender__ddb834_idx')],
            },
        ),
    ]
