# Generated by Django 4.2.5 on 2025-08-30 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('material_lines', models.JSONField(blank=True, default=list)),
                ('sequence', models.PositiveIntegerField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Speaking Journey Topic',
                'verbose_name_plural': 'Speaking Journey Topics',
                'db_table': 'speaking_journey_topics',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='TopicProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_items', to='speaking_journey.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Topic Progress',
                'verbose_name_plural': 'Topic Progress',
                'db_table': 'speaking_journey_topic_progress',
            },
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['sequence'], name='speaking_jo_sequenc_7a92af_idx'),
        ),
        migrations.AddIndex(
            model_name='topicprogress',
            index=models.Index(fields=['user'], name='speaking_jo_user_id_e8ccfe_idx'),
        ),
        migrations.AddIndex(
            model_name='topicprogress',
            index=models.Index(fields=['topic'], name='speaking_jo_topic_i_9dd126_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='topicprogress',
            unique_together={('user', 'topic')},
        ),
    ]
