# Generated by Django 4.2.5 on 2025-08-30 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaking_journey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='conversation_example',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
