# Generated by Django 4.2.5 on 2025-08-31 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('speaking_journey', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhraseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_phrase_index', models.PositiveIntegerField(default=0)),
                ('completed_phrases', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrase_progress_items', to='speaking_journey.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrase_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Phrase Progress',
                'verbose_name_plural': 'Phrase Progress',
                'db_table': 'speaking_journey_phrase_progress',
                'indexes': [models.Index(fields=['user', 'topic'], name='speaking_jo_user_id_eecb1c_idx')],
                'unique_together': {('user', 'topic')},
            },
        ),
    ]
