# Generated by Django 4.2.5 on 2025-09-02 17:04

import apps.speaking_journey.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('speaking_journey', '0004_phraseprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPhraseRecording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phrase_index', models.PositiveIntegerField()),
                ('audio_file', models.FileField(upload_to=apps.speaking_journey.models.user_phrase_audio_upload_to)),
                ('transcription', models.TextField(blank=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrase_recordings', to='speaking_journey.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_phrase_recordings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Phrase Recording',
                'verbose_name_plural': 'User Phrase Recordings',
                'db_table': 'speaking_journey_user_phrase_recordings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'topic'], name='speaking_jo_user_id_ae3ec6_idx'), models.Index(fields=['topic', 'phrase_index'], name='speaking_jo_topic_i_01c518_idx'), models.Index(fields=['user', 'topic', 'phrase_index'], name='speaking_jo_user_id_a289f5_idx')],
            },
        ),
    ]
