# Generated by Django 4.2.5 on 2025-09-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaking_journey', '0005_userphraserecording'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicprogress',
            name='fluency_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topicprogress',
            name='grammar_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topicprogress',
            name='listening_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topicprogress',
            name='pronunciation_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topicprogress',
            name='vocabulary_completed',
            field=models.BooleanField(default=False),
        ),
    ]
