# Generated by Django 4.2.5 on 2025-09-06 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speaking_journey', '0011_vocab_session_and_score'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='vocabularypracticesession',
            new_name='speaking_jo_user_id_561421_idx',
            old_name='sj_vocab_user_topic_idx',
        ),
        migrations.RenameIndex(
            model_name='vocabularypracticesession',
            new_name='speaking_jo_session_121da9_idx',
            old_name='sj_vocab_session_idx',
        ),
    ]
