# Generated by Django 4.2.5 on 2025-09-16 07:51

import apps.speaking_journey.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('speaking_journey', '0012_rename_sj_vocab_user_topic_idx_speaking_jo_user_id_561421_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicprogress',
            name='conversation_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topicprogress',
            name='conversation_total_score',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserConversationRecording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('turn_index', models.PositiveIntegerField()),
                ('role', models.CharField(blank=True, default='', max_length=8)),
                ('audio_file', models.FileField(upload_to=apps.speaking_journey.models.user_conversation_audio_upload_to)),
                ('transcription', models.TextField(blank=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_recordings', to='speaking_journey.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_conversation_recordings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Conversation Recording',
                'verbose_name_plural': 'User Conversation Recordings',
                'db_table': 'speaking_journey_user_conversation_recordings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'topic'], name='speaking_jo_user_id_84bec1_idx'), models.Index(fields=['topic', 'turn_index'], name='speaking_jo_topic_i_dea200_idx'), models.Index(fields=['user', 'topic', 'turn_index'], name='speaking_jo_user_id_eb704c_idx')],
            },
        ),
    ]
