# Generated by Django 4.2.5 on 2025-09-20 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('speaking_journey', '0013_topicprogress_conversation_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicprogress',
            name='listening_total_score',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ListeningPracticeSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('questions', models.JSONField(blank=True, default=list)),
                ('total_questions', models.IntegerField(default=0)),
                ('current_index', models.IntegerField(default=0)),
                ('correct_count', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_sessions', to='speaking_journey.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Listening Practice Session',
                'verbose_name_plural': 'Listening Practice Sessions',
                'db_table': 'speaking_journey_listening_sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'topic'], name='speaking_jo_user_id_afab15_idx'), models.Index(fields=['session_id'], name='speaking_jo_session_04886d_idx')],
            },
        ),
    ]
