# Generated by Django 4.2.5 on 2025-10-08 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('speaking_journey', '0014_topicprogress_listening_total_score_and_more'),
    ]

    operations = [
        # Note: grammar_completed and grammar_total_score already exist from migration 0006
        # Only creating the GrammarPracticeSession model
        migrations.CreateModel(
            name='GrammarPracticeSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('questions', models.JSONField(blank=True, default=list)),
                ('total_questions', models.IntegerField(default=0)),
                ('current_index', models.IntegerField(default=0)),
                ('correct_count', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grammar_sessions', to='speaking_journey.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grammar_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grammar Practice Session',
                'verbose_name_plural': 'Grammar Practice Sessions',
                'db_table': 'speaking_journey_grammar_sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'topic'], name='speaking_jo_grammar_usr_top_idx'), models.Index(fields=['session_id'], name='speaking_jo_grammar_sess_idx')],
            },
        ),
    ]
