# Generated by Django 4.2.5 on 2025-10-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaking_journey', '0015_grammar_practice_session'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='grammarpracticesession',
            new_name='speaking_jo_user_id_595126_idx',
            old_name='speaking_jo_grammar_usr_top_idx',
        ),
        migrations.RenameIndex(
            model_name='grammarpracticesession',
            new_name='speaking_jo_session_ab80b7_idx',
            old_name='speaking_jo_grammar_sess_idx',
        ),
        migrations.AddField(
            model_name='topicprogress',
            name='grammar_total_score',
            field=models.IntegerField(default=0),
        ),
    ]
