# Generated manually for AI Coach persistent cache

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('speaking_journey', '0016_rename_speaking_jo_grammar_usr_top_idx_speaking_jo_user_id_595126_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachAnalysisCache',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='coach_cache', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('analysis_data', models.JSONField(help_text='Complete coach analysis JSON')),
                ('generated_at', models.DateTimeField(auto_now=True, help_text='When this analysis was generated')),
                ('expires_at', models.DateTimeField(help_text='When this cache expires (12 hours from generation)')),
                ('is_ai_generated', models.BooleanField(default=False, help_text='True if generated by Gemini AI, False if heuristic')),
            ],
            options={
                'verbose_name': 'Coach Analysis Cache',
                'verbose_name_plural': 'Coach Analysis Caches',
                'db_table': 'speaking_journey_coach_cache',
            },
        ),
        migrations.AddIndex(
            model_name='coachanalysiscache',
            index=models.Index(fields=['expires_at'], name='speaking_jo_expires_c9a8f4_idx'),
        ),
    ]
