# Generated by Django 4.2.5 on 2025-10-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaking_journey', '0018_english_level_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='coachanalysiscache',
            new_name='speaking_jo_expires_fc0e9f_idx',
            old_name='speaking_jo_expires_c9a8f4_idx',
        ),
        migrations.AlterField(
            model_name='topic',
            name='difficulty',
            field=models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], db_index=True, default='INTERMEDIATE', max_length=12),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='english_level',
            field=models.CharField(blank=True, choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default=None, max_length=12, null=True),
        ),
    ]
