# Generated by Django 4.2.5 on 2025-10-15 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_chatmodeusage'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatmodeusage',
            new_name='analytics_c_user_id_1ab818_idx',
            old_name='analytics_c_user_id_5f8a9c_idx',
        ),
        migrations.RenameIndex(
            model_name='chatmodeusage',
            new_name='analytics_c_mode_ce2ea6_idx',
            old_name='analytics_c_mode_7d2b4e_idx',
        ),
        migrations.RenameIndex(
            model_name='chatmodeusage',
            new_name='analytics_c_is_acti_0ee244_idx',
            old_name='analytics_c_is_acti_3c9f1a_idx',
        ),
    ]
