# Generated by Django 4.2.5 on 2025-10-12 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_group_groupmessage'),
        ('authentication', '0002_add_last_activity_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Batam cultural group the user belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='users.group'),
        ),
    ]
